export const COLUMNS = [
  { field: "objectid", headerName: "Location ID", width: 200 },
  { field: "applicant", headerName: "Applicant", width: 200 },
  { field: "address", headerName: "Address", width: 200 },
  { field: "approved", headerName: "Approved", width: 200 },
  { field: "block", headerName: "Block", width: 200 },
  { field: "blocklot", headerName: "Blocklot", width: 200 },
  { field: "cnn", headerName: "CNN", width: 200 },
  { field: "expirationdate", headerName: "Expiration Date", width: 200 },
  { field: "facilitytype", headerName: "Facility Type", width: 200 },
  { field: "fooditems", headerName: "Food Items", width: 200 },
  { field: "latitude", headerName: "Latitude", width: 200 },
  {
    field: "locationdescription",
    headerName: "Location Description",
    width: 200,
  },
  { field: "longitude", headerName: "Longitude", width: 200 },
  { field: "lot", headerName: "Lot", width: 200 },
  { field: "permit", headerName: "Permit", width: 200 },
  { field: "priorpermit", headerName: "Prior Permit", width: 200 },
  { field: "received", headerName: "Received", width: 200 },
  { field: "schedule", headerName: "Schedule", width: 200 },
  { field: "status", headerName: "Status", width: 200 },
  { field: "x", headerName: "X", width: 200 },
  { field: "y", headerName: "Y", width: 200 },
];
